# Generated by Django 2.2.7 on 2019-11-25 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grants', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='GrantYears',
        ),
    ]
